In [1]:
import tensorflow as tf
from pprint import pprint
import random
from tqdm import tqdm

In [2]:
pathTFrecords = '2.Malwares/tfrecords/'
filePattern = pathTFrecords+'*.tfrecords'

In [3]:
def parser(input):
    name_to_feature  = {
        'label': tf.io.FixedLenFeature([],tf.int64),
        'packet1' : tf.io.FixedLenFeature([],tf.string),
        'packet2' : tf.io.FixedLenFeature([],tf.string),
    }
    return tf.io.parse_single_example(input, name_to_feature)
    

In [4]:
def decode_record(record):
    packet1 = record['packet1']
    packet2 = record['packet2']
    label = record['label']
    return (packet1, packet2), label


In [5]:
listOfFiles = tf.data.TFRecordDataset.list_files(filePattern)
dataset = tf.data.TFRecordDataset(listOfFiles,buffer_size=100)

In [6]:
decoded_dataset = []
labels = []
#try:
for record in tqdm(dataset):
    parsed_record = parser(record)
    decoded_record, label = decode_record(parsed_record)
    decoded_dataset.append(decoded_record)
    labels.append(label)
#except:
 #   print('lol it broke!')
print("fini !")
        
dataset = []

428422it [05:16, 1353.83it/s]fini !



In [7]:
from sklearn.utils import shuffle
X,y = shuffle(decoded_dataset, labels)
print(len(X))
print(len(y))
pprint(X[:10]) #échantillon randomisé
pprint(y[:10]) #échantillon randomisé


428422
428422
[(<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x000:\xdc@\x00\x80\x06GU\x93 T\xa5@\xecO\xe5Tq\x00P\xf1\xb2\xf6i\x00\x00\x00\x00p\x02\xfa\xf0\xd2\xb9\x00\x00\x02\x04\x05\xb4\x01\x01\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>,
  <tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x000:\xdc@\x00\x80\x06GU\x93 T\xa5@\xecO\xe5Tq\x00P\xf1\xb2\xf6i\x00\x00\x00\x00p\x02\xfa\xf0\xd2\xb9\x00\x00\x02\x04\x05\xb4\x01\x01\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>),
 (<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x00D"0@\x00 \x06\x8b-\x01\x01\xd1\xd8\x01\x02\xd9{r\\\x00\x15-,\xec\xab-F\xefQ\x80\x18\x1cHo\x16\x00\x00\x01\x01\x08\n\xc6\

In [8]:
import copy
#print(tf.keras.backend.get_value())
Xbackup = copy.deepcopy(X)

In [9]:
for i,peerPacket in tqdm(enumerate(X)):
    newDataSetItem = []
    #pprint(peerPacket)
    for packet in peerPacket:
        byteToint = []
        for octet in tf.keras.backend.get_value(packet):
            byteToint.append(octet)
        #print(byteToint)
        newDataSetItem.append(byteToint)
    X[i] = newDataSetItem
pprint(X[:10])
        

428422it [00:33, 12742.75it/s]
[[[69,
   0,
   0,
   48,
   58,
   220,
   64,
   0,
   128,
   6,
   71,
   85,
   147,
   32,
   84,
   165,
   64,
   236,
   79,
   229,
   84,
   113,
   0,
   80,
   241,
   178,
   246,
   105,
   0,
   0,
   0,
   0,
   112,
   2,
   250,
   240,
   210,
   185,
   0,
   0,
   2,
   4,
   5,
   180,
   1,
   1,
   4,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  [69,
   0,
   0,
   48,
   58,
   220,
   64,
   0,
   128,
   6,
   71,
   85,
   147,
   32,
   84,
   165,
   64,
   236,
   79,
   229,
   84,
   113,
   0,
   80,
   241,
   178,
   246,
   105,
   0,
   0,
   0,
   0,
   112,
   2,
   250,
   240,
   210,
   185,
   0,
   0,
   2,
   4,
   5,
   180,
   1,
   1,


In [10]:
import numpy as np
#pprint(X[:10])
X = np.asarray(X)
y = np.asarray(y)
print(X.shape)


(428422, 2, 100)


In [11]:
pprint(len(X[1][1]))

100


In [12]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Activation, Flatten, Conv1D, MaxPooling2D,Dense

In [13]:
model = Sequential()

#1 couche con1D de 32 filtres de taille 5
model.add(Conv1D(32,2,activation='relu',input_shape=(2,100)))
# activation maps

#flatten
model.add(Flatten())

#1 couche Dense de 50 
model.add(Dense(50))

#1 couche Dense de 100 
model.add(Dense(100))


model.add(Dense(2,activation='softmax')) #2 sorties possibles 1 ou 0

#model.add(MaxPooling2D(pool_size=(2, 2)))

model.summary()

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 1, 32)             6432      
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 50)                1650      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 202       
Total params: 13,384
Trainable params: 13,384
Non-trainable params: 0
_________________________________________________________________


In [14]:
import datetime
%reload_ext tensorboard
!rm -rf logs/
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
model.fit(X, y,batch_size=32,epochs=10,validation_split=0.1, callbacks=[tensorboard_callback])
model.save('/code/3.Modeles/modeldeepnids1.model')

Epoch 1/10
12050/12050 [==============================] - 30s 2ms/step - loss: 0.1022 - accuracy: 0.9977 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 2/10
12050/12050 [==============================] - 28s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 3/10
12050/12050 [==============================] - 24s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 4/10
12050/12050 [==============================] - 24s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 5/10
12050/12050 [==============================] - 24s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 6/10
12050/12050 [==============================] - 25s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 7/10
12050/12050 [==============================] - 26s 2ms/step - l

In [16]:
%tensorboard --logdir logs/fit --port=6006
from tensorboard import notebook
notebook.list() # View open TensorBoard instances