In [66]:
import tensorflow as tf
from pprint import pprint
import random

In [67]:
pathTFrecords = '2.Malwares/tfrecords/'
filePattern = pathTFrecords+'*.tfrecords'

In [68]:
def parser(input):
    name_to_feature  = {
        'label': tf.io.FixedLenFeature([],tf.int64),
        'packet1' : tf.io.FixedLenFeature([],tf.string),
        'packet2' : tf.io.FixedLenFeature([],tf.string),
    }
    return tf.io.parse_single_example(input, name_to_feature)
    

In [69]:
def decode_record(record):
    packet1 = record['packet1']
    packet2 = record['packet2']
    label = record['label']
    return (packet1, packet2, label)


In [70]:
listOfFiles = tf.data.TFRecordDataset.list_files(filePattern)
dataset = tf.data.TFRecordDataset(listOfFiles,buffer_size=100)

In [71]:
decoded_dataset = []
try:
    for record in dataset:
        parsed_record = parser(record)
        decoded_record = decode_record(parsed_record)
        decoded_dataset.append(decoded_record)
except:
    print('lol it broke!')
print("fini !")
        
dataset = []

lol it broke!
fini !


In [72]:
random.shuffle(decoded_dataset)
pprint(decoded_dataset[:10]) #échantillon randomisé

<class 'list'>
[(<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x00(\x00\x00@\x00/\x06\xd24\xb8\xad\xd9(\x93 T\xa5\x01\xbb\x17\xbe\x00\x00\x00\x00\x9e".\xcaP\x14\x00\x00O\xcf\x00\x00\xaa\xaa\x00\x00O\xcf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>,
  <tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x00(\x00\x00@\x00/\x06\xd24\xb8\xad\xd9(\x93 T\xa5\x01\xbb\x17\xbe\x00\x00\x00\x00\x9e".\xcaP\x14\x00\x00O\xcf\x00\x00\xaa\xaa\x00\x00O\xcf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>,
  <tf.Tensor: shape=(), dtype=int64, numpy=9>),
 (<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x008n<@\x00 \x06\x92W\x01\x02/\xd3\x01\x01(W\x0c\xea4\xa2e\x00\