In [10]:
import tensorflow as tf
from pprint import pprint

In [11]:
pathTFrecords = '2.Malwares/tfrecords/'
filePattern = pathTFrecords+'*.tfrecords'

In [13]:
def parser(input):
    name_to_feature  = {
        'label': tf.io.FixedLenFeature([],tf.int64),
        'packet1' : tf.io.FixedLenFeature([],tf.string),
        'packet2' : tf.io.FixedLenFeature([],tf.string),
    }
    return tf.io.parse_single_example(input, name_to_feature)
    

In [15]:
def decode_record(record):
    packet1 = record['packet1']
    packet2 = record['packet2']
    label = record['label']
    return (packet1, packet2, label)


In [16]:
listOfFiles = tf.data.TFRecordDataset.list_files(filePattern)
dataset = tf.data.TFRecordDataset(listOfFiles,buffer_size=10000 ,num_parallel_reads=8)

In [17]:
dataset = dataset.shuffle(buffer_size=10000)

In [24]:
dataset = dataset.map(parser)

In [26]:
for i in dataset:
    pprint(decode_record(i))

int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x004\xd7\xba@\x00 \x06!\x15\x01\x01\xc1<\x01\x02\x9e\xb5\xa3q\x00P\xf2\x14,>\x88g\xb9\x8b\x80\x10\xfe\x88\x1a\x81\x00\x00\x01\x01\x08\n\xb2\xd0\xe95\xc4"\x97\x8d{;\xaf\x9c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x004\xd7\x85@\x00 \x06!J\x01\x01\xc1<\x01\x02\x9e\xb5\xa3q\x00P\xf2\x14,>\x88hc;\x80\x10\xfe\x88B\xdb\x00\x00\x01\x01\x08\n\xb2\xd1\x07w\xc4"\xa7@M\x90\xa1\x16\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x0045F@\x00 \x06\x88\xcc\x01\x01\xa2\x9d\x01\x02\xf8\x11P\xcf\x00P\x8e\xd5M\x90+\x0e\x7f\xcf\x

KeyboardInterrupt: 