In [81]:
import tensorflow as tf
from pprint import pprint
import random
from tqdm import tqdm

In [82]:
pathTFrecords = '2.Malwares/tfrecords/'
pathTFrecordsTest = '2.Malwares/test/'
filePattern = pathTFrecords+'*.tfrecords'
filePatternTest = pathTFrecordsTest+'*.tfrecords'

In [83]:
def parser(input):
    name_to_feature  = {
        'label': tf.io.FixedLenFeature([],tf.int64),
        'packet1' : tf.io.FixedLenFeature([],tf.string),
        'packet2' : tf.io.FixedLenFeature([],tf.string),
    }
    return tf.io.parse_single_example(input, name_to_feature)
    

In [84]:
def decode_record(record):
    packet1 = record['packet1']
    packet2 = record['packet2']
    label = record['label']
    return (packet1, packet2), label


In [85]:
listOfFiles = tf.data.TFRecordDataset.list_files(filePattern)
listOfTestFiles = tf.data.TFRecordDataset.list_files(filePatternTest)
dataset = tf.data.TFRecordDataset(listOfFiles,buffer_size=100)
testDataset = tf.data.TFRecordDataset(listOfTestFiles,buffer_size=100)

In [86]:
decoded_dataset = []
labels = []

#try:
for record in tqdm(dataset):
    parsed_record = parser(record)
    decoded_record, label = decode_record(parsed_record)
    decoded_dataset.append(decoded_record)
    labels.append(label)

#except:
 #   print('lol it broke!')
print("fini !")
        
dataset = []

428422it [05:16, 1354.66it/s]fini !



In [87]:
decoded_datasetTest = []
labelsTest = []

for record in tqdm(testDataset):
    parsed_record = parser(record)
    decoded_record, label = decode_record(parsed_record)
    decoded_datasetTest.append(decoded_record)
    labelsTest.append(label)
print('Fini ! testDataset')

testDataset = []

47340it [00:34, 1376.62it/s]Fini ! testDataset



In [88]:
from sklearn.utils import shuffle
X,y = shuffle(decoded_dataset, labels)
Xtest,ytest = shuffle(decoded_datasetTest, labelsTest)
print(len(X))
print(len(y))
pprint(X[:10]) #échantillon randomisé
pprint(y[:10]) #échantillon randomisé


428422
428422
[(<tf.Tensor: shape=(), dtype=string, numpy=b"E\x00\x004\x157@\x00\x80\x06\xe2\x8f\n\x00\x02l>K\xb8F\xe1*\x1f\x90!\x84\xdf\xb4\x00\x00\x00\x00\x80\x02P\x00\x1a'\x00\x00\x02\x04\x05\xb4\x01\x03\x03\x00\x01\x01\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00">,
  <tf.Tensor: shape=(), dtype=string, numpy=b"E\x00\x004\x158@\x00\x80\x06\xe2\x8e\n\x00\x02l>K\xb8F\xe1*\x1f\x90!\x84\xdf\xb4\x00\x00\x00\x00\x80\x02P\x00\x1a'\x00\x00\x02\x04\x05\xb4\x01\x03\x03\x00\x01\x01\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00">),
 (<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x004]\x1a@\x00\x80\x06\xda-\n\x00\x02l]\xbdYS\xea+\x1f\x90\xa6\xe5\x8e[\x00\x00\x00\x00\x80\x02P\x00\x1c\x9f\

In [89]:
import copy
#print(tf.keras.backend.get_value())
Xbackup = copy.deepcopy(X)

In [90]:
for i,peerPacket in tqdm(enumerate(X)):
    newDataSetItem = []
    #pprint(peerPacket)
    for packet in peerPacket:
        byteToint = []
        for octet in tf.keras.backend.get_value(packet):
            byteToint.append(octet)
        #print(byteToint)
        newDataSetItem.append(byteToint)
    X[i] = newDataSetItem
pprint(X[:10])
        

428422it [00:32, 13004.17it/s]
[[[69,
   0,
   0,
   52,
   21,
   55,
   64,
   0,
   128,
   6,
   226,
   143,
   10,
   0,
   2,
   108,
   62,
   75,
   184,
   70,
   225,
   42,
   31,
   144,
   33,
   132,
   223,
   180,
   0,
   0,
   0,
   0,
   128,
   2,
   80,
   0,
   26,
   39,
   0,
   0,
   2,
   4,
   5,
   180,
   1,
   3,
   3,
   0,
   1,
   1,
   4,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  [69,
   0,
   0,
   52,
   21,
   56,
   64,
   0,
   128,
   6,
   226,
   142,
   10,
   0,
   2,
   108,
   62,
   75,
   184,
   70,
   225,
   42,
   31,
   144,
   33,
   132,
   223,
   180,
   0,
   0,
   0,
   0,
   128,
   2,
   80,
   0,
   26,
   39,
   0,
   0,
   2,
   4,
   5,
   180,
   1,
   3,
   3,
   0,
  

In [91]:
for i,peerPacket in tqdm(enumerate(Xtest)):
    newDataSetItem = []
    #pprint(peerPacket)
    for packet in peerPacket:
        byteToint = []
        for octet in tf.keras.backend.get_value(packet):
            byteToint.append(octet)
        #print(byteToint)
        newDataSetItem.append(byteToint)
    Xtest[i] = newDataSetItem
pprint(Xtest[:10])

47340it [00:03, 13879.27it/s]
[[[69,
   0,
   0,
   52,
   21,
   55,
   64,
   0,
   128,
   6,
   226,
   143,
   10,
   0,
   2,
   108,
   62,
   75,
   184,
   70,
   225,
   42,
   31,
   144,
   33,
   132,
   223,
   180,
   0,
   0,
   0,
   0,
   128,
   2,
   80,
   0,
   26,
   39,
   0,
   0,
   2,
   4,
   5,
   180,
   1,
   3,
   3,
   0,
   1,
   1,
   4,
   2,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  [69,
   0,
   0,
   52,
   21,
   56,
   64,
   0,
   128,
   6,
   226,
   142,
   10,
   0,
   2,
   108,
   62,
   75,
   184,
   70,
   225,
   42,
   31,
   144,
   33,
   132,
   223,
   180,
   0,
   0,
   0,
   0,
   128,
   2,
   80,
   0,
   26,
   39,
   0,
   0,
   2,
   4,
   5,
   180,
   1,
   3,
   3,
   0,
   

In [92]:
import numpy as np
#pprint(X[:10])
X = np.asarray(X)
y = np.asarray(y)
print(X.shape)




(428422, 2, 100)


In [99]:
Xtest = np.array(Xtest)
ytest = np.array(ytest)
print(Xtest.shape)


(47340, 2, 100)


In [93]:
pprint(len(X[1][1]))

100


In [94]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Activation, Flatten, Conv1D, MaxPooling2D,Dense

In [100]:
model = Sequential()

#1 couche con1D de 32 filtres de taille 5
model.add(Conv1D(32,2,activation='relu',input_shape=(2,100)))
# activation maps

#flatten
model.add(Flatten())

#1 couche Dense de 50 
model.add(Dense(50))

#1 couche Dense de 100 
model.add(Dense(100))


model.add(Dense(2,activation='softmax')) #2 sorties possibles 1 ou 0

#model.add(MaxPooling2D(pool_size=(2, 2)))

model.summary()

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_10 (Conv1D)           (None, 1, 32)             6432      
_________________________________________________________________
flatten_10 (Flatten)         (None, 32)                0         
_________________________________________________________________
dense_30 (Dense)             (None, 50)                1650      
_________________________________________________________________
dense_31 (Dense)             (None, 100)               5100      
_________________________________________________________________
dense_32 (Dense)             (None, 2)                 202       
Total params: 13,384
Trainable params: 13,384
Non-trainable params: 0
_________________________________________________________________


In [101]:
import datetime
%reload_ext tensorboard
!rm -rf logs/
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)


In [102]:
model.fit(X, y,epochs=10,validation_split=0.1, callbacks=[tensorboard_callback])
model.save('/code/3.Modeles/modeldeepnids1.model')

Epoch 1/10
12050/12050 [==============================] - 32s 3ms/step - loss: 0.2514 - accuracy: 0.9958 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 2/10
12050/12050 [==============================] - 27s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 3/10
12050/12050 [==============================] - 24s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 4/10
12050/12050 [==============================] - 24s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 5/10
12050/12050 [==============================] - 24s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 6/10
12050/12050 [==============================] - 23s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - val_loss: 0.0000e+00 - val_accuracy: 1.0000
Epoch 7/10
12050/12050 [==============================] - 23s 2ms/step - l

In [53]:
%tensorboard --logdir logs/ --host=0.0.0.0

In [104]:
score = model.evaluate(Xtest,ytest, verbose=1)
print(f'Test loss: {score[0]} / Test accuracy: {score[1]}')


1480/1480 [==============================] - 3s 2ms/step - loss: 0.0000e+00 - accuracy: 1.0000
Test loss: 0.0 / Test accuracy: 1.0
