In [22]:
import tensorflow as tf
from pprint import pprint
import random
from tqdm import tqdm

In [23]:
pathTFrecords = '2.Malwares/tfrecords/'
filePattern = pathTFrecords+'*.tfrecords'

In [24]:
def parser(input):
    name_to_feature  = {
        'label': tf.io.FixedLenFeature([],tf.int64),
        'packet1' : tf.io.FixedLenFeature([],tf.string),
        'packet2' : tf.io.FixedLenFeature([],tf.string),
    }
    return tf.io.parse_single_example(input, name_to_feature)
    

In [25]:
def decode_record(record):
    packet1 = record['packet1']
    packet2 = record['packet2']
    label = record['label']
    return (packet1, packet2, label)


In [26]:
listOfFiles = tf.data.TFRecordDataset.list_files(filePattern)
dataset = tf.data.TFRecordDataset(listOfFiles,buffer_size=100)

In [27]:
decoded_dataset = []
#try:
for record in tqdm(dataset):
    parsed_record = parser(record)
    decoded_record = decode_record(parsed_record)
    decoded_dataset.append(decoded_record)
#except:
 #   print('lol it broke!')
print("fini !")
        
dataset = []

378572it [04:32, 1389.85it/s]fini !



In [28]:
random.shuffle(decoded_dataset)
print(len(decoded_dataset))
pprint(decoded_dataset[:10]) #échantillon randomisé

378572
[(<tf.Tensor: shape=(), dtype=string, numpy=b"E\x00\x00,B\r\x00\x00@\x06}\x13^\x17Q)\n\x00\x02l\x00P\xe6vk\x8d\x06\x01\x93z'\xe2`\x12\xff\xff\xc8\xb8\x00\x00\x02\x04\x05\xb4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00">,
  <tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x00(B\x0e\x00\x00@\x06}\x16^\x17Q)\n\x00\x02l\x00P\xe6vk\x8d\x06\x02\x93z+\xbcP\x10\xff\xff\xdc\x9b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'>,
  <tf.Tensor: shape=(), dtype=int64, numpy=1>),
 (<tf.Tensor: shape=(), dtype=string, numpy=b'E\x00\x05\xdc\xa9\xd3@\x00 \x06\x89\xbb\x01\x02\x10R\x01\x01\x0f9\x00\x8b\xa6\x8c\xa4\x96\xb4mt